import turtle
n = int(input("Введите количество квадратов "))
l = int(input("Введите длину стороны квадрата "))
turtle.left(-90)
turtle.shape('triangle')
for i in range(n):
    print("Черчу квадрат ", i+1)
    print("Длина стороны ", (l * (i+1)))
    turtle.forward(l * (i+1))
    turtle.left(90)
    turtle.forward(l * (i+1))
    turtle.left(90)
    turtle.forward(l * (i+1))
    turtle.left(90)
    turtle.forward(l * (i+1))
    turtle.penup()
    turtle.left(270)
    turtle.forward(l / 2)
    turtle.left(90)
    turtle.forward(l / 2)
    turtle.left(90)
    turtle.pendown()
else:
    print("Всё")
turtle.mainloop()